services:
  - type: web
    name: fastapi-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: AIzaSyAM7RjSyQqB7mFI4_R3s2bO4Mb2H4XJRO0
        sync: false
      